# Generated by Django 2.1.1 on 2018-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userids', models.CharField(max_length=20)),
                ('posttext', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('profname', models.CharField(max_length=20)),
                ('profpic', models.TextField()),
                ('proftext', models.CharField(max_length=100)),
            ],
        ),
    ]
