# Generated by Django 2.1.1 on 2018-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='usiusi',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
