# Generated by Django 2.1.1 on 2018-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180916_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='profpicup',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
